name: Check
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    needs: [init]
    strategy:
      matrix:
        version: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.version }}
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm run test
  secret:
    needs: [init]
    runs-on: ubuntu-latest
    steps:
      - name: Print secret
        run: echo ${{ secrets.TEST }}